spring.application.name=ChatApp


spring.data.mongodb.uri = YOUR_MONGODB_URI
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = YOUR_GMAIL
spring.mail.password = **** **** ****
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

# Keep-Alive Configuration (Set RENDER_EXTERNAL_URL in Render dashboard)
app.render.url=${RENDER_EXTERNAL_URL:http://localhost:8080}